---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wirekube-operator
  namespace: wirekube-system
  labels:
    app: wirekube-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wirekube-operator
  template:
    metadata:
      labels:
        app: wirekube-operator
    spec:
      serviceAccountName: wirekube-operator
      terminationGracePeriodSeconds: 10
      containers:
        - name: operator
          image: ghcr.io/wirekube/operator:latest
          imagePullPolicy: Always
          command:
            - /operator
          args:
            - --leader-elect
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
      securityContext:
        runAsNonRoot: true
