---
apiVersion: v1
kind: Namespace
metadata:
  name: wirekube-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wirekube-operator
  namespace: wirekube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wirekube-operator
rules:
  # WireKube CRDs
  - apiGroups: [wirekube.io]
    resources: [wirekubemeshes, wirekubepeers]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [wirekube.io]
    resources: [wirekubemeshes/status, wirekubepeers/status]
    verbs: [get, update, patch]
  - apiGroups: [wirekube.io]
    resources: [wirekubemeshes/finalizers, wirekubepeers/finalizers]
    verbs: [update]
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, list, watch]
  # Events
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
  # Leader election
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wirekube-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wirekube-operator
subjects:
  - kind: ServiceAccount
    name: wirekube-operator
    namespace: wirekube-system
