//go:build !ignore_autogenerated

/*
Copyright 2024 WireKube Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalRelaySpec) DeepCopyInto(out *ExternalRelaySpec) {
	*out = *in
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalRelaySpec.
func (in *ExternalRelaySpec) DeepCopy() *ExternalRelaySpec {
	if in == nil {
		return nil
	}
	out := new(ExternalRelaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRelaySpec) DeepCopyInto(out *ManagedRelaySpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(RelayResources)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRelaySpec.
func (in *ManagedRelaySpec) DeepCopy() *ManagedRelaySpec {
	if in == nil {
		return nil
	}
	out := new(ManagedRelaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelayResources) DeepCopyInto(out *RelayResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelayResources.
func (in *RelayResources) DeepCopy() *RelayResources {
	if in == nil {
		return nil
	}
	out := new(RelayResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelaySpec) DeepCopyInto(out *RelaySpec) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalRelaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Managed != nil {
		in, out := &in.Managed, &out.Managed
		*out = new(ManagedRelaySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelaySpec.
func (in *RelaySpec) DeepCopy() *RelaySpec {
	if in == nil {
		return nil
	}
	out := new(RelaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireKubeMesh) DeepCopyInto(out *WireKubeMesh) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireKubeMesh.
func (in *WireKubeMesh) DeepCopy() *WireKubeMesh {
	if in == nil {
		return nil
	}
	out := new(WireKubeMesh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireKubeMesh) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireKubeMeshList) DeepCopyInto(out *WireKubeMeshList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WireKubeMesh, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireKubeMeshList.
func (in *WireKubeMeshList) DeepCopy() *WireKubeMeshList {
	if in == nil {
		return nil
	}
	out := new(WireKubeMeshList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireKubeMeshList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireKubeMeshSpec) DeepCopyInto(out *WireKubeMeshSpec) {
	*out = *in
	if in.STUNServers != nil {
		in, out := &in.STUNServers, &out.STUNServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Relay != nil {
		in, out := &in.Relay, &out.Relay
		*out = new(RelaySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireKubeMeshSpec.
func (in *WireKubeMeshSpec) DeepCopy() *WireKubeMeshSpec {
	if in == nil {
		return nil
	}
	out := new(WireKubeMeshSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireKubeMeshStatus) DeepCopyInto(out *WireKubeMeshStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireKubeMeshStatus.
func (in *WireKubeMeshStatus) DeepCopy() *WireKubeMeshStatus {
	if in == nil {
		return nil
	}
	out := new(WireKubeMeshStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireKubePeer) DeepCopyInto(out *WireKubePeer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireKubePeer.
func (in *WireKubePeer) DeepCopy() *WireKubePeer {
	if in == nil {
		return nil
	}
	out := new(WireKubePeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireKubePeer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireKubePeerList) DeepCopyInto(out *WireKubePeerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WireKubePeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireKubePeerList.
func (in *WireKubePeerList) DeepCopy() *WireKubePeerList {
	if in == nil {
		return nil
	}
	out := new(WireKubePeerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireKubePeerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireKubePeerSpec) DeepCopyInto(out *WireKubePeerSpec) {
	*out = *in
	if in.AllowedIPs != nil {
		in, out := &in.AllowedIPs, &out.AllowedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireKubePeerSpec.
func (in *WireKubePeerSpec) DeepCopy() *WireKubePeerSpec {
	if in == nil {
		return nil
	}
	out := new(WireKubePeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireKubePeerStatus) DeepCopyInto(out *WireKubePeerStatus) {
	*out = *in
	if in.LastHandshake != nil {
		in, out := &in.LastHandshake, &out.LastHandshake
		*out = (*in).DeepCopy()
	}
	if in.PeerTransports != nil {
		in, out := &in.PeerTransports, &out.PeerTransports
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireKubePeerStatus.
func (in *WireKubePeerStatus) DeepCopy() *WireKubePeerStatus {
	if in == nil {
		return nil
	}
	out := new(WireKubePeerStatus)
	in.DeepCopyInto(out)
	return out
}
