---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wirekube-agent
  namespace: wirekube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wirekube-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - wirekube.io
  resources:
  - wirekubepeers
  verbs:
  - get
  - list
  - create
  - patch
  - update
- apiGroups:
  - wirekube.io
  resources:
  - wirekubepeers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - wirekube.io
  resources:
  - wirekubemeshes
  verbs:
  - get
  - list
  - update
- apiGroups:
  - wirekube.io
  resources:
  - wirekubemeshes/status
  verbs:
  - get
  - patch
- apiGroups:
  - wirekube.io
  resources:
  - wirekubegateways
  verbs:
  - get
  - list
- apiGroups:
  - wirekube.io
  resources:
  - wirekubegateways/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wirekube-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wirekube-agent
subjects:
- kind: ServiceAccount
  name: wirekube-agent
  namespace: wirekube-system
