{{- if and .Values.relay.enabled .Values.relayWs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: wirekube-relay-ws
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wirekube.relayWs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: relay
    {{- include "wirekube.labels" . | nindent 4 }}
  {{- with .Values.relayWs.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.relayWs.service.type }}
  selector:
    {{- include "wirekube.relayWs.selectorLabels" . | nindent 4 }}
  ports:
    - name: http-websocket
      port: {{ .Values.relayWs.port }}
      targetPort: {{ .Values.relayWs.port }}
      protocol: TCP
      {{- if eq .Values.relayWs.service.type "NodePort" }}
      nodePort: {{ .Values.relayWs.service.nodePort }}
      {{- end }}
{{- end }}
