---
apiVersion: wirekube.io/v1alpha1
kind: WireKubeMesh
metadata:
  name: default
spec:
  listenPort: 51822
  interfaceName: wire_kube
  mtu: 1420
  stunServers:
    - stun:stun.l.google.com:19302
    - stun:stun1.l.google.com:19302
    - stun:stun.cloudflare.com:3478
