apiVersion: v1
kind: ServiceAccount
metadata:
  name: wirekube-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wirekube.agent.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
    {{- include "wirekube.labels" . | nindent 4 }}
